# Kubernetes deployment file for OODT RabbitMQ server
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  labels:
    stack: acce
    component: rabbitmq
spec:
  type: NodePort
  ports:
  - port: 5672
    targetPort: 5672
    protocol: TCP
    name: rmq-client-port
  - port: 15672
    targetPort: 15672
    protocol: TCP
    name: rmq-web-port
  # the selector identifies the set of pods to load-balance against
  selector:
    stack: acce
    component: rabbitmq
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: oodt-rabbitmq
spec:
  replicas: 1
  template:
    metadata:
      labels:
        stack: acce
        component: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: acce/oodt-rabbitmq:2.0
        ports:
        - containerPort: 5672
        - containerPort: 15672
        env:
        # example connection URL for rabbitmq message producers - override as needed
        - name: RABBITMQ_USER_URL
          value: "amqp://oodt-user:changeit@localhost/%2f"
        - name: RABBITMQ_ADMIN_URL
          value: "http://oodt-admin:changeit@localhost:15672"
      volumes:
      - name: rmq-producer-script
        hostPath:
          # FIXME
          path: /Users/cinquini/eclipse-workspace/labcas-nlst/scripts/nlst_workflow_driver.py:/usr/local/oodt/rabbitmq/nlst_workflow_driver.py